// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okzbbtgduzjqkcqungnu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9remJidGdkdXpqcWtjcXVuZ251Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NjU1MzMsImV4cCI6MjA2ODU0MTUzM30.NByKNp0dc3g5EuFEwEFQhgCIeeaLFPAn5mpopnaiDDU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});